# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'federated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\x12\tfederated\"B\n\nClientInfo\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0bnum_samples\x18\x02 \x01(\x05\x12\x0c\n\x04host\x18\x03 \x01(\t\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\x0cRoundRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x10\n\x08round_id\x18\x02 \x01(\x05\"C\n\x0cModelWeights\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\x12\x10\n\x08round_id\x18\x02 \x01(\x05\x12\x10\n\x08\x63hecksum\x18\x03 \x01(\t\"\x91\x01\n\x0bLocalUpdate\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07weights\x18\x02 \x01(\x0c\x12\x10\n\x08round_id\x18\x03 \x01(\x05\x12\x13\n\x0bnum_samples\x18\x04 \x01(\x05\x12\x10\n\x08\x63hecksum\x18\x05 \x01(\t\x12\x12\n\ntrain_loss\x18\x06 \x01(\x02\x12\x11\n\ttrain_acc\x18\x07 \x01(\x02\"\xc2\x01\n\x0eTrainingStatus\x12\x15\n\rcurrent_round\x18\x01 \x01(\x05\x12\x17\n\x0fglobal_accuracy\x18\x02 \x01(\x02\x12\x13\n\x0bglobal_loss\x18\x03 \x01(\x02\x12\x16\n\x0e\x61\x63tive_clients\x18\x04 \x01(\x05\x12\x13\n\x0bis_training\x18\x05 \x01(\x08\x12\x14\n\x0ctotal_rounds\x18\x06 \x01(\x05\x12(\n\x07\x63lients\x18\x07 \x03(\x0b\x32\x17.federated.ClientStatus\"\x84\x01\n\x0c\x43lientStatus\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x10\n\x08is_alive\x18\x02 \x01(\x08\x12\x15\n\rhas_responded\x18\x03 \x01(\x08\x12\x11\n\tlast_loss\x18\x04 \x01(\x02\x12\x10\n\x08last_acc\x18\x05 \x01(\x02\x12\x13\n\x0bnum_samples\x18\x06 \x01(\x05\"\x07\n\x05\x45mpty2\x83\x02\n\x10\x46\x65\x64\x65ratedService\x12\x31\n\x08Register\x12\x15.federated.ClientInfo\x1a\x0e.federated.Ack\x12\x42\n\x0eGetGlobalModel\x12\x17.federated.RoundRequest\x1a\x17.federated.ModelWeights\x12\x36\n\x0cSubmitUpdate\x12\x16.federated.LocalUpdate\x1a\x0e.federated.Ack\x12@\n\x11GetTrainingStatus\x12\x10.federated.Empty\x1a\x19.federated.TrainingStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTINFO']._serialized_start=30
  _globals['_CLIENTINFO']._serialized_end=96
  _globals['_ACK']._serialized_start=98
  _globals['_ACK']._serialized_end=137
  _globals['_ROUNDREQUEST']._serialized_start=139
  _globals['_ROUNDREQUEST']._serialized_end=190
  _globals['_MODELWEIGHTS']._serialized_start=192
  _globals['_MODELWEIGHTS']._serialized_end=259
  _globals['_LOCALUPDATE']._serialized_start=262
  _globals['_LOCALUPDATE']._serialized_end=407
  _globals['_TRAININGSTATUS']._serialized_start=410
  _globals['_TRAININGSTATUS']._serialized_end=604
  _globals['_CLIENTSTATUS']._serialized_start=607
  _globals['_CLIENTSTATUS']._serialized_end=739
  _globals['_EMPTY']._serialized_start=741
  _globals['_EMPTY']._serialized_end=748
  _globals['_FEDERATEDSERVICE']._serialized_start=751
  _globals['_FEDERATEDSERVICE']._serialized_end=1010
# @@protoc_insertion_point(module_scope)
